/** Full Garmin FIT SDK exercise category enum values (curated for gym use) */
export const GARMIN_EXERCISE_ENUMS = [
  // ── Bench Press ──────────────────────────────────────────────────────────────
  'BARBELL_BENCH_PRESS',
  'DUMBBELL_BENCH_PRESS',
  'INCLINE_BARBELL_BENCH_PRESS',
  'INCLINE_DUMBBELL_BENCH_PRESS',
  'DECLINE_BARBELL_BENCH_PRESS',
  'DECLINE_DUMBBELL_BENCH_PRESS',
  'CLOSE_GRIP_BARBELL_BENCH_PRESS',
  'DUMBBELL_FLOOR_PRESS',
  'INCLINE_DUMBBELL_FLYE',
  'DECLINE_DUMBBELL_FLYE',

  // ── Squat ─────────────────────────────────────────────────────────────────────
  'BARBELL_BACK_SQUAT',
  'BARBELL_FRONT_SQUAT',
  'GOBLET_SQUAT',
  'OVERHEAD_SQUAT',
  'BODY_WEIGHT_SQUAT',
  'LEG_PRESS',
  'HACK_SQUAT',
  'BULGARIAN_SPLIT_SQUAT',
  'PISTOL_SQUAT',
  'SUMO_SQUAT',
  'BOX_SQUAT',
  'PAUSE_SQUAT',
  'ZERCHER_SQUAT',

  // ── Deadlift ──────────────────────────────────────────────────────────────────
  'BARBELL_DEADLIFT',
  'ROMANIAN_DEADLIFT',
  'SUMO_DEADLIFT',
  'SINGLE_LEG_DEADLIFT',
  'STIFF_LEG_DEADLIFT',
  'DUMBBELL_DEADLIFT',
  'TRAP_BAR_DEADLIFT',
  'DUMBBELL_ROMANIAN_DEADLIFT',
  'SNATCH_GRIP_DEADLIFT',

  // ── Shoulder Press ────────────────────────────────────────────────────────────
  'BARBELL_SHOULDER_PRESS',
  'DUMBBELL_SHOULDER_PRESS',
  'SEATED_BARBELL_SHOULDER_PRESS',
  'SEATED_DUMBBELL_SHOULDER_PRESS',
  'PUSH_PRESS',
  'ARNOLD_PRESS',
  'MILITARY_PRESS',
  'Z_PRESS',
  'LANDMINE_PRESS',

  // ── Pull / Row ────────────────────────────────────────────────────────────────
  'LAT_PULLDOWN',
  'WIDE_GRIP_LAT_PULLDOWN',
  'CLOSE_GRIP_LAT_PULLDOWN',
  'REVERSE_GRIP_LAT_PULLDOWN',
  'PULL_UP',
  'CHIN_UP',
  'NEUTRAL_GRIP_PULL_UP',
  'ASSISTED_PULL_UP',
  'BARBELL_ROW',
  'DUMBBELL_ROW',
  'SEATED_CABLE_ROW',
  'T_BAR_ROW',
  'SINGLE_ARM_DUMBBELL_ROW',
  'CHEST_SUPPORTED_ROW',
  'MEADOWS_ROW',
  'INVERTED_ROW',
  'PENDLAY_ROW',

  // ── Push-up ───────────────────────────────────────────────────────────────────
  'PUSH_UP',
  'INCLINE_PUSH_UP',
  'DECLINE_PUSH_UP',
  'CLOSE_GRIP_PUSH_UP',
  'DIAMOND_PUSH_UP',
  'ARCHER_PUSH_UP',
  'PIKE_PUSH_UP',
  'PSEUDO_PLANCHE_PUSH_UP',

  // ── Bicep ─────────────────────────────────────────────────────────────────────
  'BARBELL_BICEPS_CURL',
  'DUMBBELL_BICEPS_CURL',
  'HAMMER_CURL',
  'PREACHER_CURL',
  'CABLE_BICEPS_CURL',
  'CONCENTRATION_CURL',
  'INCLINE_DUMBBELL_CURL',
  'CROSS_BODY_HAMMER_CURL',
  'REVERSE_BARBELL_CURL',
  'ZOTTMAN_CURL',
  'SPIDER_CURL',

  // ── Tricep ────────────────────────────────────────────────────────────────────
  'SKULL_CRUSHER',
  'CABLE_TRICEPS_EXTENSION',
  'DUMBBELL_TRICEPS_EXTENSION',
  'CLOSE_GRIP_BENCH_PRESS',
  'TRICEPS_PUSHDOWN',
  'OVERHEAD_TRICEPS_EXTENSION',
  'TRICEPS_DIP',
  'KICKBACK',
  'JM_PRESS',
  'TATE_PRESS',

  // ── Shoulder accessory ────────────────────────────────────────────────────────
  'LATERAL_RAISE',
  'FRONT_RAISE',
  'FACE_PULL',
  'REVERSE_FLY',
  'CABLE_LATERAL_RAISE',
  'SHOULDER_SHRUG',
  'UPRIGHT_ROW',
  'BAND_PULL_APART',
  'PRONE_Y_RAISE',
  'PRONE_T_RAISE',
  'PRONE_W_RAISE',

  // ── Lunge ─────────────────────────────────────────────────────────────────────
  'BARBELL_LUNGE',
  'DUMBBELL_LUNGE',
  'WALKING_LUNGE',
  'REVERSE_LUNGE',
  'SIDE_LUNGE',
  'CURTSY_LUNGE',
  'STEP_UP',
  'BARBELL_STEP_UP',
  'DUMBBELL_STEP_UP',
  'LATERAL_STEP_UP',

  // ── Hip / Glute ───────────────────────────────────────────────────────────────
  'BARBELL_HIP_THRUST',
  'DUMBBELL_HIP_THRUST',
  'GLUTE_BRIDGE',
  'CABLE_KICKBACK',
  'DONKEY_KICK',
  'FIRE_HYDRANT',
  'CLAMSHELL',
  'HIP_ABDUCTION',
  'HIP_ADDUCTION',
  'SINGLE_LEG_GLUTE_BRIDGE',
  'FROG_PUMP',
  'LATERAL_BAND_WALK',

  // ── Leg isolation ─────────────────────────────────────────────────────────────
  'LEG_CURL',
  'SEATED_LEG_CURL',
  'PRONE_LEG_CURL',
  'LEG_EXTENSION',
  'CALF_RAISE',
  'SEATED_CALF_RAISE',
  'DONKEY_CALF_RAISE',
  'TIBIALIS_RAISE',
  'NORDIC_HAMSTRING_CURL',

  // ── Core ──────────────────────────────────────────────────────────────────────
  'PLANK',
  'SIDE_PLANK',
  'CRUNCH',
  'SIT_UP',
  'DEAD_BUG',
  'BIRD_DOG',
  'RUSSIAN_TWIST',
  'LEG_RAISE',
  'BICYCLE_CRUNCH',
  'HOLLOW_BODY_HOLD',
  'AB_WHEEL_ROLLOUT',
  'CABLE_CRUNCH',
  'HANGING_LEG_RAISE',
  'HANGING_KNEE_RAISE',
  'TOE_TOUCH',
  'V_UP',
  'DRAGON_FLAG',
  'PALLOF_PRESS',
  'WOOD_CHOP',
  'REVERSE_CRUNCH',
  'WINDMILL',

  // ── Cable / Machine ───────────────────────────────────────────────────────────
  'CABLE_CHEST_FLY',
  'CABLE_CROSSOVER',
  'CABLE_CHEST_PRESS',
  'CHEST_FLY',
  'PEC_DECK',
  'MACHINE_CHEST_PRESS',
  'MACHINE_ROW',
  'MACHINE_SHOULDER_PRESS',
  'MACHINE_LEG_PRESS',
  'MACHINE_LEG_CURL',
  'MACHINE_LEG_EXTENSION',
  'MACHINE_HIP_ABDUCTION',
  'MACHINE_HIP_ADDUCTION',
  'MACHINE_CALF_RAISE',
  'CABLE_PULL_THROUGH',
  'CABLE_ROW',
  'HIGH_CABLE_CURL',
  'LOW_CABLE_CURL',

  // ── Olympic / Power ───────────────────────────────────────────────────────────
  'POWER_CLEAN',
  'POWER_SNATCH',
  'HANG_CLEAN',
  'HANG_SNATCH',
  'CLEAN_AND_JERK',
  'BARBELL_SNATCH',

  // ── Athletic / Functional ─────────────────────────────────────────────────────
  'BURPEE',
  'MOUNTAIN_CLIMBER',
  'JUMPING_JACK',
  'BOX_JUMP',
  'BOX_STEP_UP',
  'BROAD_JUMP',
  'DEPTH_JUMP',
  'JUMP_SQUAT',
  'TUCK_JUMP',
  'KETTLEBELL_SWING',
  'KETTLEBELL_GOBLET_SQUAT',
  'KETTLEBELL_DEADLIFT',
  'KETTLEBELL_CLEAN',
  'KETTLEBELL_PRESS',
  'KETTLEBELL_SNATCH',
  'KETTLEBELL_TURKISH_GET_UP',
  'FARMER_CARRY',
  'SUITCASE_CARRY',
  'OVERHEAD_CARRY',
  'SLED_PUSH',
  'SLED_PULL',
  'BATTLE_ROPE',
  'TIRE_FLIP',
  'SANDBAG_CARRY',

  // ── Stretching / Mobility ─────────────────────────────────────────────────────
  'GOOD_MORNING',
  'HIP_FLEXOR_STRETCH',
  'PIGEON_POSE',
  'WORLD_GREATEST_STRETCH',
  'INCHWORM',
  'THORACIC_ROTATION',
  'ANKLE_CIRCLES',
  'HIP_CIRCLES',
] as const;

export type GarminExerciseEnum = (typeof GARMIN_EXERCISE_ENUMS)[number];
