/** Curated list from Garmin FIT SDK exercise category enum values */
export const GARMIN_EXERCISE_ENUMS = [
  // Bench Press
  'BARBELL_BENCH_PRESS', 'DUMBBELL_BENCH_PRESS', 'INCLINE_BARBELL_BENCH_PRESS',
  'INCLINE_DUMBBELL_BENCH_PRESS', 'DECLINE_BARBELL_BENCH_PRESS', 'DECLINE_DUMBBELL_BENCH_PRESS',
  'CLOSE_GRIP_BARBELL_BENCH_PRESS', 'DUMBBELL_FLOOR_PRESS',
  // Squat
  'BARBELL_BACK_SQUAT', 'BARBELL_FRONT_SQUAT', 'GOBLET_SQUAT', 'OVERHEAD_SQUAT',
  'BODY_WEIGHT_SQUAT', 'LEG_PRESS', 'HACK_SQUAT', 'BULGARIAN_SPLIT_SQUAT', 'PISTOL_SQUAT',
  // Deadlift
  'BARBELL_DEADLIFT', 'ROMANIAN_DEADLIFT', 'SUMO_DEADLIFT', 'SINGLE_LEG_DEADLIFT',
  'STIFF_LEG_DEADLIFT', 'DUMBBELL_DEADLIFT',
  // Shoulder Press
  'BARBELL_SHOULDER_PRESS', 'DUMBBELL_SHOULDER_PRESS', 'SEATED_BARBELL_SHOULDER_PRESS',
  'SEATED_DUMBBELL_SHOULDER_PRESS', 'PUSH_PRESS', 'ARNOLD_PRESS', 'MILITARY_PRESS',
  // Pull / Row
  'LAT_PULLDOWN', 'WIDE_GRIP_LAT_PULLDOWN', 'CLOSE_GRIP_LAT_PULLDOWN',
  'PULL_UP', 'CHIN_UP', 'NEUTRAL_GRIP_PULL_UP', 'ASSISTED_PULL_UP',
  'BARBELL_ROW', 'DUMBBELL_ROW', 'SEATED_CABLE_ROW', 'T_BAR_ROW', 'SINGLE_ARM_DUMBBELL_ROW',
  // Push-up
  'PUSH_UP', 'INCLINE_PUSH_UP', 'DECLINE_PUSH_UP', 'CLOSE_GRIP_PUSH_UP', 'DIAMOND_PUSH_UP',
  // Bicep
  'BARBELL_BICEPS_CURL', 'DUMBBELL_BICEPS_CURL', 'HAMMER_CURL',
  'PREACHER_CURL', 'CABLE_BICEPS_CURL', 'CONCENTRATION_CURL',
  // Tricep
  'SKULL_CRUSHER', 'CABLE_TRICEPS_EXTENSION', 'DUMBBELL_TRICEPS_EXTENSION',
  'CLOSE_GRIP_BENCH_PRESS', 'TRICEPS_PUSHDOWN', 'OVERHEAD_TRICEPS_EXTENSION', 'TRICEPS_DIP',
  // Shoulder accessory
  'LATERAL_RAISE', 'FRONT_RAISE', 'FACE_PULL', 'REVERSE_FLY',
  'CABLE_LATERAL_RAISE', 'SHOULDER_SHRUG', 'UPRIGHT_ROW',
  // Lunge
  'BARBELL_LUNGE', 'DUMBBELL_LUNGE', 'WALKING_LUNGE', 'REVERSE_LUNGE',
  'SIDE_LUNGE', 'CURTSY_LUNGE', 'STEP_UP',
  // Hip / Glute
  'BARBELL_HIP_THRUST', 'DUMBBELL_HIP_THRUST', 'GLUTE_BRIDGE',
  'CABLE_KICKBACK', 'DONKEY_KICK', 'FIRE_HYDRANT', 'CLAMSHELL',
  // Leg isolation
  'LEG_CURL', 'SEATED_LEG_CURL', 'LEG_EXTENSION', 'CALF_RAISE', 'SEATED_CALF_RAISE',
  // Core
  'PLANK', 'SIDE_PLANK', 'CRUNCH', 'SIT_UP', 'DEAD_BUG', 'BIRD_DOG',
  'RUSSIAN_TWIST', 'LEG_RAISE', 'BICYCLE_CRUNCH', 'HOLLOW_BODY_HOLD', 'AB_WHEEL_ROLLOUT',
  // Cable / Machine
  'CABLE_CHEST_FLY', 'CABLE_CROSSOVER', 'CABLE_CHEST_PRESS', 'CHEST_FLY',
  'PEC_DECK', 'MACHINE_CHEST_PRESS', 'MACHINE_ROW', 'MACHINE_SHOULDER_PRESS', 'MACHINE_LEG_PRESS',
  // Athletic
  'BURPEE', 'MOUNTAIN_CLIMBER', 'JUMPING_JACK', 'BOX_JUMP', 'BOX_STEP_UP',
  'KETTLEBELL_SWING', 'KETTLEBELL_GOBLET_SQUAT', 'FARMER_CARRY', 'SLED_PUSH', 'BATTLE_ROPE',
] as const;

export type GarminExerciseEnum = (typeof GARMIN_EXERCISE_ENUMS)[number];
